### PR TITLE
Expose gaps commands as library

### PR DESCRIPTION
**Pull request by cwarden**
Expose init, download, and upload functions so gaps can be used in other
javascript programs.

Update clone and download functions to take an optional destination
directory.  Update download function to return the project object so the
path to the actual project, based on the project's name, can be
retrieved.

Update upload function to take an optional source directory.  When
uploading, set path in the manifest to the actual path in case the
directory has been moved and the path inside the manifest file is no
longer correct.

### CODE REVIEW

**Comment by cwarden** [comment]
If you have a preferred testing framework, I'd be happy to include tests for these changes.

**Comment by danthareja** [comment]
I love this @cwarden! Very nice use some underscore methods.  _.constant(project) is just the pattern I was looking for.

Tests are certainly on the todo list. Would you mind firing up a few for your great work? I'm super happy to pull these changes in.

**Comment by danthareja** [comment]
Merged! I'll add tests eventually. Thanks for your contribution!

**Comment by cwarden** [comment]
@danthareja, sorry for not getting back to this to add the tests.  I started working on the tests for the download module, but put it aside when the changes started getting rather intrusive since none of the internal functions are exposed.  Here's where I left off: e1eac802380f05213b34d6ca9c8794dc665b3287

**Pull request merged**
