### PR TITLE
large refactor, various improvements

### PR DESCRIPTION
**Pull request by shrugs**
I'm at intern at Google this summer; thanks for your work on node-google-apps-script. I used it a bunch but ran into some small issues so I forked it and added some fixes and features.
- I changed the `init` command to `auth` to better describe what it does
- `gaps init` now creates a folder structure and a `config.json`
  - you no longer need a `manifest.json` on disk; it's downloaded at upload-time for merging with the representation on disk. `config.json` includes things like which subdirectory the code is in, the drive `fileId`, etc
- changed semantics so that, when pushing code to drive, your local copy is always `master`
  - meaning that after upload, whatever was on disk will be in Google Drive
  - this means no sync issues because files that exist are edited, new files are created, and unused files are deleted
  - this is ideal for automated workflows because the command can't fail for odd reasons
- removed download functionality
  - if your source code is in source control, downloading a project from apps script doesn't make much sense
  - you also lose the faux-directory hierarchy
  - it's also not compatible with the "local is master" idea above
- Adds a comprehensive quickstart
- switches to an installed application type so the authentication flow is easier; the terminal throws up a simple webserver that access the OAuth response. Now you only have to copy/paste a code if you don't have access to a web browser, namely when sshing.
- switched to `bluebird` for Promises since it's the subjectively best promise lib right now.
- used `Promise.promisify` frequently to clean up the [deferreds](https://github.com/petkaantonov/bluebird/wiki/Promise-anti-patterns)
- bumps version number to `1.0.0`; we've been using a version of this in real workflows for a few weeks now and it's been pretty stable. It's totally up to you if you want to keep the `1.0.0` or instead make it an `0.2.0` release

Sorry for the large PR on a Friday :)

### CODE REVIEW

**Comment by danthareja** [comment]
This is awesome @Shrugs!! I've seen you around the issues helping out a lot. Thank you very much for your contributions with other issues and helping me stay on top of this project and keep it alive.

I'll give it a good look over the weekend and get back to you soon.

**Comment by danthareja** [comment]
Sorry for the delay on this, @Shrugs. Thanks again for your work on this and for taking the time to submit a PR. Before merging this I want to get some insight into the workflow you had with this tool. It seems to differ quite a bit from my own initial thoughts. I like a lot of your changes and I'm totally open to merging them but first want to understand your process more and see if we can make this tool work for both workflows.

I'm most curious in the removal of `gaps download` and best practice of never editing in the web IDE. I agree that having the local copy as `master` makes a lot of sense, but how are you testing as you develop? 

As I understand, there's no way to run an app script locally. When I was developing with this tool (I'll admit I am still new to many features in the Apps Script API), I found myself `Logger.log`ing all over the place. I would have felt it as a burden to push every time I wanted to run my code. At the time, my thought was to keep `master` in the web IDE to speed up development/testing and then `gaps download` right before a version control commit.

Did you handle testing differently?

**Comment by shrugs** [comment]
Yeah, the logging situation needs to be improved. Unfortunately the Apps Script API doesn't expose logs at the moment, but if they ever integrate with Cloud Logging, that could be added to gaps.

My development workflow looks like this:
- `gaps init ...`
- Then I copy over some utilities that I always use to the src directory
- `gaps upload`
- go into the web IDE and attach a test running the latest code to a random document
- whenever I change something, upload with `gaps upload`
  - I either use gulp with a file watcher or a sublime text build system that runs `gaps upload`
- as it's uploading I tab over to my browser and reload the sidebar/extension in my document
  - usually the upload will finish before I reload the extension so it's just as smooth as editing in the web IDE

I end up logging a lot as well and just keep the web IDE open for when I need to see them, which involves a bit of tabbing between the open document, sublime, and the web IDE. I'd agree that it's a bit more cumbersome to now have another window to switch between, but working in a real editor makes that entirely worth it for me.

I wouldn't mind adding the download functionality back, but what do you think the best implementation is? 
- if you're downloading, wipe everything in `src` and replace it with files from the network
  - do we completely ignore file structure (less than ideal, since that's a large part of why this method is great)
  - do we encode the file structure into the filename somehow so that you can recreate the folders on download
    - then we run into the issue where you're trying to load `index.html` but you have to reference it as `app_views_index.html` or whatever
- you could also try merging files instead of deleting them (the functionally reverse of the upload operation)
  - if there's a file from drive called `index.html`, find that file on disk and replace its contents
  - then there's the issue of what to do about any new files you create; do they just go directly into `src`?

I couldn't think of an ideal situation for the download functionality, so I just removed it.

@danthareja 

Thanks for taking the time to check it out :)

**Comment by danthareja** [comment]
Hey @Shrugs, finally pulled this in! It was too long of a time coming, but thanks again for your solid work. The auth flow changed a little from the UI, so I just changed that around. Also, I ended up going with `gapps`, I think it makes more sense from a Google Apps perspective. I thought a bit more about downloading and kind of agree that it doesn't make anymore sense. If people complain maybe we can add it back.

I added your name under an Acknowledgements section. Right now it links to your github profile, if you want it to go somewhere else let me know!

**Comment by shrugs** [comment]
Cheers, thanks for the work on node-google-apps-script!

**Pull request merged**
