### PR TITLE
Sets minimum node version to >= 8 and makes use of some ES6 features

### PR DESCRIPTION
**Pull request by lricoy**
- Converted all `var`occurences to `const` (only one `let` was necessary)
- Converted all callbacks to use arrow functions instead of `function` syntax. Did not change top-level function definitions.

### CODE REVIEW

**Comment by lricoy** [comment]
Still working on this

**Review by aurelienshz — APPROVED** [review]
LGTM. I don't see any point where we're using the value of `this` inside a closure so I don't think switching to arrow functions is going to be an issue.

**Comment by aurelienshz** [comment]
On a side note, I'm wondering if we could get rid of Lodash. If we require Node >= 8, we have Array.prototype.some and Array.prototype.find for example (regarding examples taken only from your PR's diff)

**Comment by lricoy** [comment]
Totally agree. I didn't want to remove it on this one just to keep the
changes to a minimum but indeed was planning to do it in the future.

Em Qui, 14 de dez de 2017 19:08, Aurélien Schiltz <notifications@github.com>
escreveu:

**Pull request merged**
